import { test, expect } from '@playwright/test';

test.describe('Incident Management Tool E2E', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('should toggle language between English and Japanese', async ({ page }) => {
    // The button shows the language we can switch TO.
    const langButton = page.getByRole('button', { name: /English|日本語/ });
    
    // Check current state by looking at the button text
    const initialText = await langButton.innerText();
    
    if (initialText.includes('日本語')) {
      // Current language is English, switch to Japanese
      await langButton.click();
      await expect(page.getByRole('heading', { name: 'サービスダッシュボード' })).toBeVisible();
      
      // Switch back to English
      await langButton.click();
      await expect(page.getByRole('heading', { name: 'Service Dashboard' })).toBeVisible();
    } else {
      // Current language is Japanese, switch to English
      await langButton.click();
      await expect(page.getByRole('heading', { name: 'Service Dashboard' })).toBeVisible();
      
      // Switch back to Japanese
      await langButton.click();
      await expect(page.getByRole('heading', { name: 'サービスダッシュボード' })).toBeVisible();
    }
  });

  test('should create and then edit an incident', async ({ page }) => {
    const testTitle = `Test Incident ${Date.now()}`;
    const updatedTitle = `${testTitle} (Updated)`;

    // 1. Navigate to Report Issue
    await page.getByRole('link', { name: /Report Issue|インシデント報告/ }).click();
    await expect(page.getByRole('heading', { name: /Report New Incident|新規インシデントの報告/ })).toBeVisible();

    // 2. Fill form and submit
    await page.getByPlaceholder(/summary|要約/).fill(testTitle);
    await page.getByPlaceholder(/happened|起きたか|説明/).fill('This is a test description generated by Playwright.');
    await page.getByRole('button', { name: /Submit|送信/ }).click();

    // 3. Wait for navigation back to list and check if title exists
    await expect(page.getByText(testTitle)).toBeVisible();

    // 4. Click the action button in the row to go to detail
    const row = page.locator('tr').filter({ hasText: testTitle });
    await row.getByRole('button').click();

    // 5. Verify detailed view
    await expect(page.getByRole('heading', { name: testTitle })).toBeVisible();

    // 6. Click Edit button
    await page.getByRole('button', { name: /Edit|編集/ }).click();

    // 7. Update title and save
    await page.getByLabel(/Title|タイトル/).fill(updatedTitle);
    await page.getByRole('button', { name: /Save|保存/ }).click();

    // 8. Check for success toast and updated title
    await expect(page.getByText(/success|更新しました/i).first()).toBeVisible();
    await expect(page.getByRole('heading', { name: updatedTitle })).toBeVisible();
  });

  test('should delete an incident', async ({ page }) => {
    const deleteTitle = `Delete Me ${Date.now()}`;

    // Create one first
    await page.getByRole('link', { name: /Report Issue|インシデント報告/ }).click();
    await page.getByPlaceholder(/summary|要約/).fill(deleteTitle);
    await page.getByRole('button', { name: /Submit|送信/ }).click();
    await expect(page.getByText(deleteTitle)).toBeVisible();

    // Go to detail
    const row = page.locator('tr').filter({ hasText: deleteTitle });
    await row.getByRole('button').click();

    // Trigger delete
    page.on('dialog', dialog => dialog.accept()); // Handle confirmation dialog
    await page.getByRole('button', { name: /Delete|削除/ }).click();

    // Verify redirected back to list and item is gone
    await expect(page.getByRole('heading', { name: /Incidents|インシデント/ })).toBeVisible();
    await expect(page.getByText(deleteTitle)).not.toBeVisible();
  });

  test('should update incident status', async ({ page }) => {
    const statusTitle = `Status Test ${Date.now()}`;

    // 1. Create an incident
    await page.getByRole('link', { name: /Report Issue|インシデント報告/ }).click();
    await page.getByPlaceholder(/summary|要約/).fill(statusTitle);
    await page.getByRole('button', { name: /Submit|送信/ }).click();
    await expect(page.getByText(statusTitle)).toBeVisible();

    // 2. Go to detail
    const row = page.locator('tr').filter({ hasText: statusTitle });
    await row.getByRole('button').click();
    await expect(page.getByRole('heading', { name: statusTitle })).toBeVisible();

    // 3. Update status to "In Progress"
    // We can use the label we just added or the role
    await page.getByLabel(/Status Management|ステータス管理/).selectOption('In Progress');
    await page.getByRole('button', { name: /Update Status|ステータスを更新/ }).click();

    // 4. Verify success toast and that the status has changed
    await expect(page.getByText(/success|更新しました/i).first()).toBeVisible();
    
    // Check if "In Progress" or "進行中" is selected
    await expect(page.getByLabel(/Status Management|ステータス管理/)).toHaveValue('In Progress');
  });
});
